import test from'node:test';import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{bomToCSV,createBOM,exportKiCadNetlist,importKiCadNetlist,KiCadBridgeError,parseEngineeringValue}from'../src/index.js';
const fixture=await readFile(new URL('./fixtures/divider.net',import.meta.url),'utf8');
test('imports supported KiCad components, nets, and metadata',()=>{const{circuit,warnings,unmapped}=importKiCadNetlist(fixture);assert.equal(circuit.ground,'GND');assert.equal(circuit.metadata.name,'Voltage Divider');assert.equal(circuit.components.length,3);assert.equal(circuit.components.find(item=>item.id==='R1').resistance,1000);assert.equal(circuit.components.find(item=>item.id==='R2').resistance,2200);assert.equal(circuit.components.find(item=>item.id==='V1').voltage,10);assert.equal(warnings.length,1);assert.equal(unmapped[0].ref,'U1');assert.equal(circuit.extensions['org.opencircuitlabs.kicad'].componentMetadata.R1.fields.Tolerance,'1%');});
test('can reject unsupported symbols in strict mode',()=>{assert.throws(()=>importKiCadNetlist(fixture,{onUnsupported:'error'}),/U1/);});
test('parses common engineering notation by quantity',()=>{assert.equal(parseEngineeringValue('4.7kΩ','resistance'),4700);assert.ok(Math.abs(parseEngineeringValue('100nF','capacitance')-100e-9)<1e-20);assert.ok(Math.abs(parseEngineeringValue('2.2mH','inductance')-2.2e-3)<1e-15);assert.equal(parseEngineeringValue('10V','voltage'),10);assert.equal(parseEngineeringValue('bad','resistance'),undefined);});
test('exports deterministic KiCad XML with escaped labels',()=>{const circuit=importKiCadNetlist(fixture).circuit;circuit.nodes.find(node=>node.id==='VOUT').label='Output & sense';const first=exportKiCadNetlist(circuit,{date:'fixed'}),second=exportKiCadNetlist(circuit,{date:'fixed'});assert.equal(first,second);assert.match(first,/Output &amp; sense/);assert.match(first,/<comp ref="R1">/);});
test('round trips supported connectivity and values',()=>{const original=importKiCadNetlist(fixture).circuit;const xml=exportKiCadNetlist(original,{date:'fixed'});const roundtrip=importKiCadNetlist(xml).circuit;assert.deepEqual(roundtrip.components.map(({id,type,from,to,...rest})=>({id,type,from,to,value:rest.resistance??rest.voltage})),original.components.map(({id,type,from,to,...rest})=>({id,type,from,to,value:rest.resistance??rest.voltage})));});
test('creates grouped BOM data and CSV',()=>{const circuit=importKiCadNetlist(fixture).circuit;const bom=createBOM(circuit);assert.equal(bom.reduce((sum,row)=>sum+row.quantity,0),3);assert.match(bomToCSV(bom),/Quantity,References,Type,Value/);});
test('reports invalid XML and circuit references',()=>{assert.throws(()=>importKiCadNetlist('<bad/>'),KiCadBridgeError);assert.throws(()=>exportKiCadNetlist({ground:'0',nodes:[{id:'0'}],components:[{id:'R1',type:'resistor',from:'x',to:'0',resistance:1}]}),/unknown node/);});
